spring:
  profiles:
    active: dev

---
server:
  port: 8001
#mybatis配置
mybatis:
  type-aliases-package: com.fzh.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
#spring的配置
spring:
  profiles: dev
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
#Eureka配置 ,服务注册到注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhostfzh7001:7001/eureka/,http://localhostfzh7002:7002/eureka/,http://localhostfzh7003:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept-8001 #修改Eureka上的默认描述信息


management:
  endpoints:
    web:
      exposure:
        include: "info"
  endpoint:
    shutdown:
      enabled: true #打开shutdown端点
    health:
      show-details: always #获得健康中心所有指标的详细信息
#info配置
info:
  app.name: springcloud-service-news
  company.name: www.mark.com
#  build.artifactId: ${project.artifactId}
#  build.version: ${project.version}

---
server:
  port: 8001
#mybatis配置
mybatis:
  type-aliases-package: com.fzh.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
#spring的配置
spring:
  profiles: test
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb02?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
#Eureka配置 ,服务注册到注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhostfzh7001:7001/eureka/,http://localhostfzh7002:7002/eureka/,http://localhostfzh7003:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept-8001 #修改Eureka上的默认描述信息


management:
  endpoints:
    web:
      exposure:
        include: "info"
  endpoint:
    shutdown:
      enabled: true #打开shutdown端点
    health:
      show-details: always #获得健康中心所有指标的详细信息
#info配置
info:
  app.name: springcloud-service-news
  company.name: www.mark.com
#  build.artifactId: ${project.artifactId}
#  build.version: ${project.version}