spring:
  profiles:
    active: dev

---
server:
  port: 7001
spring:
  profiles: dev
  application:
    name: springcloud-config-eureka
#Eureka配置
eureka:
  instance:
    hostname: localhostfzh7001 #Eureka服务端的实例名称
  client:
    register-with-eureka: false  #表示是否向Eureka注册中心注册自己
    fetch-registry: false  #如果为false则表示自己为注册中心
    service-url:
      defaultZone: http://localhostfzh7002:7002/eureka/,http://localhostfzh7003:7003/eureka/

---
server:
  port: 7001
spring:
  profiles: test
  application:
    name: springcloud-config-eureka
#Eureka配置
eureka:
  instance:
    hostname: localhostfzh7001 #Eureka服务端的实例名称
  client:
    register-with-eureka: false  #表示是否向Eureka注册中心注册自己
    fetch-registry: false  #如果为false则表示自己为注册中心
    service-url:
      defaultZone: http://localhostfzh7002:7002/eureka/,http://localhostfzh7003:7003/eureka/
ne: http://localhostfzh7002:7002/eureka/,http://localhostfzh7003:7003/eureka/